name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7         # tương thích Dart >=3.0.0 <3.5.0
  url_launcher: ^6.2.5        # tương thích Dart >=3.0.0 <3.5.0
  cupertino_icons: ^1.0.5     # tương thích Dart >=3.0.0 <3.6.0

dev_dependencies:
  flutter_lints: ^3.0.1       # tương thích Dart >=3.0.0 <3.5.0
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/projects/
